name: "Example Github Actions"
description: "Example Github Actions"

author: "Example user"

branding:
  icon: git-pull-request
  color: red

inputs:
  hogefuga:
    description: "hogefuga"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"